---
- name: Download Keycloak ZIP archive
  get_url:
    url: "https://github.com/keycloak/keycloak/releases/download/{{ keycloak_version }}/keycloak-{{ keycloak_version }}.zip"
    dest: "/tmp/keycloak-{{ keycloak_version }}.zip"

- name: Create Keycloak installation directory
  file:
    path: "{{ keycloak_install_dir }}"
    state: directory

- name: Extract Keycloak ZIP archive
  unarchive:
    src: "/tmp/keycloak-{{ keycloak_version }}.zip"
    dest: "{{ keycloak_install_dir }}"
    remote_src: yes

- name: Start Keycloak
  shell: |
    nohup {{ keycloak_install_dir }}/keycloak-{{ keycloak_version }}/bin/kc.sh start-dev --hostname={{ keycloak_hostname }} > /opt/keycloak/keycloak.log 2>&1 &
  async: 30
  poll: 0
  changed_when: false
  register: keycloak_start

- name: Wait for Keycloak to start
  wait_for:
    port: 8080
    delay: 10
    timeout: 300
    state: started

- name: Cleanup downloaded files
  file:
    path: "/tmp/keycloak-{{ keycloak_version }}.zip"
    state: absent
