---
- name: Ensure PostgreSQL service is started
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Set PostgreSQL password for 'postgres' user
  ansible.builtin.shell: |
    sudo -u postgres psql -c "ALTER USER postgres PASSWORD '{{ postgres_password }}';"

- name: Create Keycloak database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: keycloak

- name: Create Keycloak database user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: keycloak
    password: "{{ postgres_password }}"
    priv: "ALL"
    db: keycloak
    role_attr_flags: LOGIN

- name: Allow local connections to PostgreSQL
  lineinfile:
    path: /etc/postgresql/15/main/pg_hba.conf
    regexp: '^host\s+all\s+all\s+127\.0\.0\.1/32\s+'
    line: 'host    all             all             127.0.0.1/32            md5'

- name: Restart PostgreSQL to apply changes
  service:
    name: postgresql
    state: restarted
