---
nexus_from_tar_on_debian12_version: "3.69.0-02"  # Example version
nexus_from_tar_on_debian12_java_version: "java11"
nexus_from_tar_on_debian12_download_url: >
  https://download.sonatype.com/nexus/3/nexus-{{ nexus_from_tar_on_debian12_version }}-{{ nexus_from_tar_on_debian12_java_version }}-unix.tar.gz
nexus_from_tar_on_debian12_install_dir: "/opt/nexus"
