- name: Install
  hosts: all
  become: true
  vars:
    nginx_version: "1.24.0"
  roles:
    - role: nginx_from_source_on_ubuntu
      vars:
        nginx_from_source_on_ubuntu_version: "{{ nginx_version }}"
      tags:
        - install
