---
- name: Ensure the system is updated
  ansible.builtin.apt:
    update_cache: true

- name: Install WireGuard
  ansible.builtin.apt:
    name: wireguard
    state: present

- name: Install WireGuard tools
  ansible.builtin.apt:
    name: wireguard-tools
    state: present

- name: Ensure WireGuard configuration directory exists
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Generate WireGuard private key
  ansible.builtin.command:
    cmd: wg genkey
  register: private_key_result
  changed_when: false

- name: Save WireGuard private key to file
  ansible.builtin.copy:
    content: "{{ private_key_result.stdout }}"
    dest: /etc/wireguard/privatekey
    mode: '0600'

- name: Set WireGuard private key
  ansible.builtin.set_fact:
    wg_private_key: "{{ private_key_result.stdout }}"

- name: Generate WireGuard public key
  ansible.builtin.command:
    cmd: "echo {{ wg_private_key }} | wg pubkey"
  register: public_key_result
  changed_when: false

- name: Save WireGuard public key to file
  ansible.builtin.copy:
    content: "{{ public_key_result.stdout }}"
    dest: /etc/wireguard/publickey
    mode: '0600'

- name: Set WireGuard public key
  ansible.builtin.set_fact:
    wg_public_key: "{{ public_key_result.stdout }}"

- name: Create WireGuard configuration file
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'

- name: Ensure WireGuard is enabled and started
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: true
    state: started
  register: wg_service_result
  failed_when: wg_service_result.failed

- name: Check WireGuard service status if failed
  ansible.builtin.command:
    cmd: systemctl status wg-quick@wg0
  when: wg_service_result.failed
  register: service_status
  changed_when: false

- name: Debug WireGuard service status
  ansible.builtin.debug:
    var: service_status.stdout
  when: wg_service_result.failed

- name: Check WireGuard service logs if failed
  ansible.builtin.command:
    cmd: journalctl -xeu wg-quick@wg0
  when: wg_service_result.failed
  register: service_logs
  changed_when: false

- name: Debug WireGuard service logs
  ansible.builtin.debug:
    var: service_logs.stdout
  when: wg_service_result.failed
