- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - libacl1-dev
    - zlib1g-dev
    - libssl-dev
    - wget
  register: apt_result
  retries: 3
  delay: 5
  until: apt_result is succeeded

- name: Download Bareos Community Edition TAR archive
  ansible.builtin.get_url:
    url: "https://download.bareos.org/next/Debian_12/bareos_24.0.0~pre606.3f332687a.orig.tar.gz"
    dest: "/tmp/bareos-24.0.0~pre606.3f332687a.orig.tar.gz"
    mode: '0644'

- name: Create Bareos installation directory
  ansible.builtin.file:
    path: "/opt/bareos"
    state: directory
  become: true

- name: Extract Bareos TAR archive
  ansible.builtin.unarchive:
    src: "/tmp/bareos-24.0.0~pre606.3f332687a.orig.tar.gz"
    dest: "/opt/bareos"
    remote_src: true

- name: Find the extracted configure script
  ansible.builtin.find:
    paths: "/opt/bareos"
    recurse: true
    patterns: "configure"
  register: found_dirs

- name: Compile and install Bareos
  ansible.builtin.shell: |
    cd {{ item.path | dirname }}
    ./configure
    make
    sudo make install
  loop: "{{ found_dirs.files }}"
  when: found_dirs.matched > 0

- name: Check contents of extracted Bareos directory
  ansible.builtin.command:
    cmd: "ls -R /opt/bareos"
  register: bareos_dir_contents

- debug:
    var: bareos_dir_contents.stdout

- name: Ensure Bareos configuration directory exists
  ansible.builtin.file:
    path: "/etc/bareos"
    state: directory
  become: true

- name: Copy default configuration files
  ansible.builtin.copy:
    src: "/opt/bareos/bareos-24.0.0~pre606.3f332687a/config"
    dest: "/etc/bareos/"
    remote_src: true
    mode: '0644'
    directory_mode: '0755'
  become: true
  ignore_errors: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Bareos services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - bareos-dir.service
    - bareos-fd.service
    - bareos-sd.service

- name: Cleanup downloaded files
  ansible.builtin.file:
    path: "/tmp/bareos-24.0.0~pre606.3f332687a.orig.tar.gz"
    state: absent
