- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - libxml2-dev
    - libjson-c-dev
    - libgtest-dev
    - build-essential
    - cmake
    - git
    - libjansson-dev
    - libssl-dev
    - libsystemd-dev
    - python3-dev
    - pkg-config
    - zlib1g-dev
    - libreadline-dev
    - libncurses5-dev
    - libpam0g-dev
    - liblzo2-dev
    - libacl1-dev
    - google-mock
    libgtest-dev
    googletest-tools
  register: apt_result
  retries: 3
  delay: 5
  until: apt_result is succeeded

- name: Download Bareos Community Edition TAR archive
  ansible.builtin.get_url:
    url: "https://github.com/bareos/bareos/archive/refs/tags/Release/23.0.2.tar.gz"
    dest: "/tmp/bareos-23.0.2.tar.gz"
    mode: '0644'

- name: Create Bareos installation directory
  ansible.builtin.file:
    path: "/opt/bareos"
    state: directory
  become: true

- name: Extract Bareos TAR archive
  ansible.builtin.unarchive:
    src: "/tmp/bareos-23.0.2.tar.gz"
    dest: "/opt/bareos"
    remote_src: true

- name: Compile and install Bareos using CMake
  ansible.builtin.shell: |
    sudo mkdir -p /opt/bareos/bareos-Release-23.0.2/build
    cd /opt/bareos/bareos-Release-23.0.2/build
    sudo cmake -DPostgreSQL_INCLUDE_DIR=/usr/include/postgresql -DPostgreSQL_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpq.so ..
    sudo make
    sudo make install
  become: true

- name: Check contents of extracted Bareos directory
  ansible.builtin.command:
    cmd: "ls -R /opt/bareos"
  register: bareos_dir_contents

- debug:
    var: bareos_dir_contents.stdout

- name: Ensure Bareos configuration directory exists
  ansible.builtin.file:
    path: "/etc/bareos"
    state: directory
  become: true

# - name: Copy default configuration files
#   ansible.builtin.copy:
#     src: "/opt/bareos/bareos-Release-23.0.2/config"
#     dest: "/etc/bareos/"
#     remote_src: true
#     mode: '0644'
#     directory_mode: '0755'
#   become: true
#   ignore_errors: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Bareos services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - bareos-dir.service
    - bareos-fd.service
    - bareos-sd.service

- name: Cleanup downloaded files
  ansible.builtin.file:
    path: "/tmp/bareos-23.0.2.tar.gz"
    state: absent
