- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    prefix: nginx-build-
  register: build_dir

- name: Install nginx build deps
  ansible.builtin.apt:
    pkg: "{{ nginx_from_source_on_ubuntu_build_deps }}"
    update_cache: false

- name: Download nginx source code archive
  ansible.builtin.get_url:
    url: "https://nginx.org/download/nginx-{{ nginx_from_source_on_ubuntu_version }}.tar.gz"
    dest: "{{ build_dir.path }}/nginx.tar.gz"
    mode: '0640'

- name: Extract archive with nginx source code
  ansible.builtin.unarchive:
    src: "{{ build_dir.path }}/nginx.tar.gz"
    dest: "{{ build_dir.path }}"
    remote_src: true

- name: Configure
  ansible.builtin.command: |
    ./configure \
    --prefix={{ nginx_from_source_on_ubuntu_workdir_path }} \
    --sbin-path={{ nginx_from_source_on_ubuntu_sbin_path }} \
    --conf-path={{ nginx_from_source_on_ubuntu_conffile_path }} \
    --http-log-path={{ nginx_from_source_on_ubuntu_logfile_path }} \
    --error-log-path={{ nginx_from_source_on_ubuntu_errlogfile_path }} \
    --with-pcre \
    --lock-path={{ nginx_from_source_on_ubuntu_lockfile_path }} \
    --pid-path={{ nginx_from_source_on_ubuntu_pidfile_path }} \
    --with-http_ssl_module \
    --with-http_image_filter_module=dynamic \
    --modules-path={{ nginx_from_source_on_ubuntu_modulesdir_path }} \
    --with-http_v2_module \
    --with-stream=dynamic \
    --with-http_addition_module \
    --with-http_mp4_module
  args:
    chdir: "{{ build_dir.path }}/nginx-{{ nginx_version }}"
  changed_when: true

- name: Build nginx
  ansible.builtin.command: make
  args:
    chdir: "{{ build_dir.path }}/nginx-{{ nginx_version }}"
  changed_when: true

- name: Install nginx
  ansible.builtin.command: make install
  args:
    chdir: "{{ build_dir.path }}/nginx-{{ nginx_version }}"
  changed_when: true

- name: Template systemd service
  ansible.builtin.template:
    src: nginx.service
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: '0640'

- name: Start and enable nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true

- name: Remove build directory
  ansible.builtin.file:
    path: "{{ build_dir.path }}"
    state: absent
