- name: Ensure dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libgdbm-dev
    - libdb5.3-dev
    - libbz2-dev
    - libexpat1-dev
    - liblzma-dev
    - tk-dev
    - wget

- name: Download Python source code
  get_url:
    url: "https://github.com/python/cpython/archive/refs/tags/v{{ python_version }}.tar.gz"
    dest: "/tmp/Python-{{ python_version }}.tar.gz"

- name: Extract Python source code
  unarchive:
    src: "/tmp/Python-{{ python_version }}.tar.gz"
    dest: "/usr/src"
    remote_src: yes

- name: Compile and install Python
  shell: |
    cd /usr/src/cpython-{{ python_version }}
    ./configure --enable-optimizations
    make -j$(nproc)
    sudo make install
  args:
    creates: /usr/local/bin/python3
  become: true

- name: Verify Python installation
  command: /usr/local/bin/python3 --version
