---
- name: Ensure SaltStack repository key directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Ensure SaltStack repository key is added
  ansible.builtin.get_url:
    url: "https://repo.saltproject.io/salt/py3/debian/12/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg"
    dest: /etc/apt/keyrings/salt-archive-keyring-2023.gpg
    mode: '0644'

- name: Add SaltStack repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/12/amd64/latest bookworm main"
    state: present
    filename: salt.list
  notify: Update apt cache

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install SaltStack Master
  ansible.builtin.apt:
    name: salt-master
    state: present
    update_cache: true

- name: Ensure SaltStack Master is running and enabled
  ansible.builtin.service:
    name: salt-master
    state: started
    enabled: true
