---
- name: Install Keycloak from ZIP on Debian
  hosts: all
  become: true
  vars:
    keycloak_from_zip_on_debian_keycloak_version: "20.0.1"
  roles:
    - role: keycloak_from_zip_on_debian
      vars:
        keycloak_from_zip_on_debian_version: "{{ keycloak_from_zip_on_debian_keycloak_version }}"
      tags:
        - install
