- name: Ensure gnupg is installed
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Ensure gnupg is installed
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Add Icinga GPG key
  ansible.builtin.apt_key:
    url: "https://packages.icinga.com/icinga.key"
    state: present

- name: Add Icinga repository
  ansible.builtin.apt_repository:
    repo: 'deb http://packages.icinga.com/debian icinga-bookworm main'
    state: present
    filename: 'icinga'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Icinga
  ansible.builtin.apt:
    name: icinga2
    state: present

- name: Start and enable Icinga service
  ansible.builtin.systemd:
    name: icinga2
    enabled: true
    state: started
