- name: Install Gitea from binary on Debian
  hosts: all
  become: true
  vars:
    gitea_version: "1.22.0"
  roles:
    - role: gitea_from_binary_on_debian
      vars:
        gitea_from_binary_on_debian_version: "{{ gitea_version }}"
      tags:
        - install
