CREATE TABLE `crs_settings` (
  `obj_id` int(11) NOT NULL DEFAULT 0,
  `syllabus` text DEFAULT NULL,
  `contact_name` varchar(255) DEFAULT NULL,
  `contact_responsibility` varchar(255) DEFAULT NULL,
  `contact_phone` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_consultation` text DEFAULT NULL,
  `activation_type` tinyint(4) NOT NULL DEFAULT 0,
  `activation_start` int(11) DEFAULT NULL,
  `activation_end` int(11) DEFAULT NULL,
  `sub_limitation_type` tinyint(4) NOT NULL DEFAULT 0,
  `sub_start` int(11) DEFAULT NULL,
  `sub_end` int(11) DEFAULT NULL,
  `sub_type` int(11) DEFAULT NULL,
  `sub_password` varchar(32) DEFAULT NULL,
  `sub_mem_limit` tinyint(4) NOT NULL DEFAULT 0,
  `sub_max_members` int(11) DEFAULT NULL,
  `sub_notify` int(11) DEFAULT NULL,
  `view_mode` tinyint(4) NOT NULL DEFAULT 0,
  `sortorder` int(11) DEFAULT NULL,
  `archive_start` int(11) DEFAULT NULL,
  `archive_end` int(11) DEFAULT NULL,
  `archive_type` int(11) DEFAULT NULL,
  `abo` tinyint(4) DEFAULT 1,
  `waiting_list` tinyint(4) NOT NULL DEFAULT 1,
  `important` text DEFAULT NULL,
  `show_members` tinyint(4) NOT NULL DEFAULT 1,
  `latitude` varchar(30) DEFAULT NULL,
  `longitude` varchar(30) DEFAULT NULL,
  `location_zoom` int(11) NOT NULL DEFAULT 0,
  `enable_course_map` tinyint(4) NOT NULL DEFAULT 0,
  `session_limit` tinyint(4) NOT NULL DEFAULT 0,
  `session_prev` bigint(20) NOT NULL DEFAULT -1,
  `session_next` bigint(20) NOT NULL DEFAULT -1,
  `reg_ac_enabled` tinyint(4) NOT NULL DEFAULT 0,
  `reg_ac` varchar(32) DEFAULT NULL,
  `status_dt` tinyint(4) DEFAULT 2,
  `auto_notification` tinyint(4) NOT NULL DEFAULT 1,
  `mail_members_type` tinyint(4) DEFAULT 1,
  `crs_start` int(11) DEFAULT NULL,
  `crs_end` int(11) DEFAULT NULL,
  `leave_end` int(11) DEFAULT NULL,
  `auto_wait` tinyint(4) NOT NULL DEFAULT 0,
  `min_members` smallint(6) DEFAULT NULL,
  `show_members_export` int(11) DEFAULT NULL,
  `timing_mode` tinyint(4) DEFAULT 0,
  `period_start` datetime DEFAULT NULL,
  `period_end` datetime DEFAULT NULL,
  `period_time_indication` int(11) NOT NULL DEFAULT 0,
  `target_group` text DEFAULT NULL,
  PRIMARY KEY (`obj_id`)
);
