- name: Install ILIAS on Debian 12
  hosts: all
  become: true
  vars:
    ilias_db_password: "your_db_password"
    ilias_admin_email: "admin@example.com"
    ilias_site_url: "http://your_ilias_site_url"
    ilias_data_dir: "/var/www/files"
    ilias_docroot: "/var/www/html/ilias"
    ilias_version: "release_9"
    mysql_root_password: "your_db_password"
  roles:
    - role: ilias_from_zip_on_debian
