---
- name: Ensure the system is updated
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install WireGuard
  ansible.builtin.apt:
    name: wireguard
    state: present

- name: Install WireGuard tools
  ansible.builtin.apt:
    name: wireguard-tools
    state: present

- name: Ensure WireGuard configuration directory exists
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Generate WireGuard private key
  ansible.builtin.command: "bash -c 'wg genkey | tee /etc/wireguard/privatekey'"
  register: wg_private_key_output
  changed_when: "'privatekey' not in wg_private_key_output.stdout"

- name: Set WireGuard private key
  ansible.builtin.set_fact:
    wg_private_key: "{{ wg_private_key_output.stdout }}"

- name: Generate WireGuard public key
  ansible.builtin.command: "bash -c 'echo {{ wg_private_key_output.stdout }} | wg pubkey | tee /etc/wireguard/publickey'"
  register: wg_public_key_output
  changed_when: "'publickey' not in wg_public_key_output.stdout"

- name: Set WireGuard public key
  ansible.builtin.set_fact:
    wg_public_key: "{{ wg_public_key_output.stdout }}"

- name: Save WireGuard keys to file
  ansible.builtin.copy:
    content: "PrivateKey: {{ wg_private_key }}\nPublicKey: {{ wg_public_key }}"
    dest: /etc/wireguard/keys
    mode: '0600'
  notify: Restart WireGuard
