---
# tasks file for wireguard

- name: Ensure the system is updated
  apt:
    update_cache: yes

- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Install WireGuard tools
  apt:
    name: wireguard-tools
    state: present

- name: Ensure WireGuard configuration directory exists
  file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Generate WireGuard private key
  command: wg genkey
  register: wg_private_key

- name: Generate WireGuard public key
  command: echo "{{ wg_private_key.stdout }}" | wg pubkey
  register: wg_public_key

- name: Save WireGuard keys to file
  copy:
    content: |
      [Interface]
      PrivateKey = {{ wg_private_key.stdout }}
      Address = 10.0.0.1/24
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
  notify: restart wireguard
