---
- name: Install Keycloak from ZIP on Debian
  hosts: all
  become: yes
  vars_files:
    - roles/common/vars/main.yaml
    - roles/postgres/vars/main.yaml
    - roles/keycloak/vars/main.yaml

  roles:
    - common
    - postgres
    - keycloak
