- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: 
      - unzip
      - openjdk-17-jdk
    state: present

- name: Create Keycloak installation directory
  ansible.builtin.file:
    path: "{{ keycloak_from_zip_on_debian_install_dir }}"
    state: directory
    mode: '0755'

- name: Download Keycloak ZIP archive
  ansible.builtin.get_url:
    url: "https://github.com/keycloak/keycloak/releases/download/{{ keycloak_from_zip_on_debian_version }}/keycloak-{{ keycloak_from_zip_on_debian_version }}.zip"
    dest: "/tmp/keycloak-{{ keycloak_from_zip_on_debian_version }}.zip"
    mode: '0644'

- name: Extract Keycloak ZIP archive
  ansible.builtin.unarchive:
    src: "/tmp/keycloak-{{ keycloak_from_zip_on_debian_version }}.zip"
    dest: "{{ keycloak_from_zip_on_debian_install_dir }}"
    remote_src: yes

- name: List contents of Keycloak installation directory
  ansible.builtin.shell: "ls -la {{ keycloak_from_zip_on_debian_install_dir }}"
  register: dir_contents

- name: Debug contents of Keycloak installation directory
  ansible.builtin.debug:
    var: dir_contents.stdout_lines

- name: Set environment variables for Keycloak
  ansible.builtin.lineinfile:
    path: /etc/profile.d/keycloak.sh
    line: 'export PATH={{ keycloak_from_zip_on_debian_install_dir }}/keycloak-{{ keycloak_from_zip_on_debian_version }}/bin:$PATH'
    create: yes
    mode: '0644'

- name: Start Keycloak
  ansible.builtin.shell: |
    nohup {{ keycloak_from_zip_on_debian_install_dir }}/keycloak-{{ keycloak_from_zip_on_debian_version }}/bin/kc.sh start-dev --hostname={{ keycloak_from_zip_on_debian_hostname }} > /opt/keycloak/keycloak.log 2>&1 &
  async: 30
  poll: 0
  changed_when: false
  register: keycloak_start

- name: Wait for Keycloak to start
  ansible.builtin.wait_for:
    path: /opt/keycloak/keycloak.log
    search_regex: 'Keycloak .* started'
    delay: 10
    timeout: 120
  register: keycloak_log

- name: Cleanup downloaded files
  ansible.builtin.file:
    path: "/tmp/keycloak-{{ keycloak_from_zip_on_debian_version }}.zip"
    state: absent
    mode: '0644'
