---
- name: Create Nexus installation directory
  ansible.builtin.file:
    path: "{{ nexus_from_tar_on_debian12_install_dir }}"
    state: directory
    mode: '0755'

- name: Download Nexus TAR file
  ansible.builtin.get_url:
    url: "{{ nexus_from_tar_on_debian12_download_url }}"
    dest: "/tmp/nexus-{{ nexus_from_tar_on_debian12_version }}-{{ nexus_from_tar_on_debian12_java_version }}-unix.tar.gz"
    mode: '0644'

- name: Extract Nexus TAR file
  ansible.builtin.unarchive:
    src: "/tmp/nexus-{{ nexus_from_tar_on_debian12_version }}-{{ nexus_from_tar_on_debian12_java_version }}-unix.tar.gz"
    dest: "{{ nexus_from_tar_on_debian12_install_dir }}"
    remote_src: true

- name: Create nexus user
  ansible.builtin.user:
    name: nexus
    home: "{{ nexus_from_tar_on_debian12_install_dir }}"
    shell: /bin/bash

- name: Set permissions on Nexus directory
  ansible.builtin.file:
    path: "{{ nexus_from_tar_on_debian12_install_dir }}"
    state: directory
    owner: nexus
    group: nexus
    recurse: true

- name: Create Nexus service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/nexus.service
    content: |
      [Unit]
      Description=Nexus service
      After=network.target

      [Service]
      Type=forking
      LimitNOFILE=65536
      ExecStart={{ nexus_from_tar_on_debian12_install_dir }}/nexus-{{ nexus_from_tar_on_debian12_version }}/bin/nexus start
      ExecStop={{ nexus_from_tar_on_debian12_install_dir }}/nexus-{{ nexus_from_tar_on_debian12_version }}/bin/nexus stop
      User=nexus
      Restart=on-abort

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  notify:
    - Enable Nexus service
    - Start Nexus service

- name: Enable Nexus service
  ansible.builtin.systemd:
    name: nexus
    enabled: true
    state: started
  when: false
