- name: Ensure installation directory exists
  ansible.builtin.file:
    path: "{{ xwiki_from_zip_on_debian_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install unzip utility
  ansible.builtin.package:
    name: unzip
    state: present
  become: true

- name: Debug network connectivity
  ansible.builtin.command:
    cmd: ping -c 4 google.com
  register: ping_output
  ignore_errors: true
  changed_when: false

- name: Debug network connectivity output
  ansible.builtin.debug:
    var: ping_output

- name: Debug DNS resolution
  ansible.builtin.command:
    cmd: nslookup nexus.xwiki.org
  register: nslookup_output
  ignore_errors: true
  changed_when: false

- name: Debug DNS resolution output
  ansible.builtin.debug:
    var: nslookup_output

- name: Download XWiki ZIP
  ansible.builtin.get_url:
    url: "{{ xwiki_from_zip_on_debian_url_base }}{{ xwiki_from_zip_on_debian_url_path }}{{ xwiki_from_zip_on_debian_url_file }}"
    dest: /tmp/xwiki.zip
    mode: '0644'
  retries: 3
  delay: 5
  register: download_result
  until: download_result is succeeded

- name: Unzip XWiki
  ansible.builtin.unarchive:
    src: /tmp/xwiki.zip
    dest: "{{ xwiki_from_zip_on_debian_install_dir }}"
    remote_src: true

- name: Set execute permissions for start script
  ansible.builtin.file:
    path: "{{ xwiki_from_zip_on_debian_install_dir }}/xwiki-platform-distribution-flavor-jetty-hsqldb-{{ xwiki_from_zip_on_debian_version }}/start_xwiki.sh"
    mode: '0755'
  when: download_result is succeeded

- name: Create systemd service file for XWiki
  ansible.builtin.template:
    src: xwiki.service.j2
    dest: /etc/systemd/system/xwiki.service
    mode: '0644'
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable and start the XWiki service
  ansible.builtin.systemd:
    name: xwiki
    enabled: true
    state: started
  become: true


- name: Enable and start the XWiki service
  ansible.builtin.systemd:
    name: xwiki
    enabled: true
    state: started
  become: true
